### PR TITLE
Update bitvec dependency to 0.22.3

### PR DESCRIPTION
**Pull request by jjpe**
This commit makes the necessary changes to update the bitvec dependency to 0.22.3.

### CODE REVIEW

**Comment by bkchr** [comment]
Please run all tests with `TRYBUILD=overwrite cargo test --all` and commit the changes. (You need to run them using 1.57)

**Comment by jjpe** [comment]
@bkchr I just did that locally. All tests pass. 
So I'm not sure what's going on with the CI/CD pipeline of this project, but apparently the issue isn't with this PR.

**Comment by koushiro** [comment]
bitvec 1.0 has been released

**Comment by bkchr** [comment]
Superseded by: https://github.com/paritytech/parity-scale-codec/pull/311

**Pull request closed without merging**
