### PR TITLE
Add dedup_len trait

### PR DESCRIPTION
**Pull request by 0xmovses**
This is a fix for https://github.com/paritytech/polkadot-sdk/issues/126

### CODE REVIEW

**Comment by bkchr** [comment]
Please revert the FMT commit.

**Comment by ggwpez** [comment]
Wait... this adds a `DecodeDedupLength` trait for `BTreeSet`? I dont think thats possible. The advantage of the `DecodeLen` is that is does *not* have to decode everything, but only a `Compact<u32>`.  
What i meant in the other issue to just remove the `impl DecodeLen for BTreeSet` and replace it with a `DecodeNonDedupLen` or so.  
cc @bkchr

**Comment by 0xmovses** [comment]
Yeah that's clearer now, let me update this.

**Comment by 0xmovses** [comment]
I don't think we need to add this here anymore, as we are just adding a more descriptive trait in `polkado-sdk`, closing this.

**Pull request closed without merging**
