### PR TITLE
replace DecodeLength with ConstrainedDecode

### PR DESCRIPTION
**Pull request by rphmeier**
I think this is more general and will be better to integrate into SRML macros.

I'm thinking that it can integrate like this (within `decl_module!` invocation):

```rust
fn my_constrained_call(
    #[constrained(|| MaximumLength(Trait::MaxItems::get()))] items: Vec<Item>,
    #[constrained(|| build_custom_constraint())] value: MyStruct,
    unconstrained: u32, // no annotation means the macro automatically inserts `NoConstraint`
) { ... }
```

### CODE REVIEW

**Comment by thiolliere** [comment]
I don't understand the final point of this, in substrate let's say for the srml-contract:put_code call 
```
		pub fn put_code(
			origin,
			#[compact] gas_limit: T::Gas,
			code: Vec<u8>
		) -> Result {
```
there is no point to restrain code size because of decoding purpose no ?

**Comment by bkchr** [comment]
I think as discussed in Riot, we can close this.

**Comment by rphmeier** [comment]
It's not _necessary_ to be secure, but it is helpful to make sure decoding can fail fast.

**Comment by bkchr** [comment]
I created an issue for this https://github.com/paritytech/parity-scale-codec/issues/112

**Pull request closed without merging**
