### PR TITLE
Provides implementations for String, Rc, Arc

### PR DESCRIPTION
**Pull request by rise0chen**

### CODE REVIEW

**Comment by bkchr** [comment]
As you already see these implementations exists and you can use them. We have put them behind features because of reasons and they will stay there.

**Comment by rise0chen** [comment]
Why discourage the usage of `String`?

It is used in `sp_version::RuntimeVersion`.

**Comment by rise0chen** [comment]
`String` needn't use  `std`.
Can we use an extra feature, like `alloc` ?

**Comment by bkchr** [comment]
There is the `full` feature that enables all the stuff. You even removed the code for that here.

**Comment by rise0chen** [comment]
yes, thinks.
I misunderstand it, I thought `full` will enable all features.

**Pull request closed without merging**
