### PR TITLE
chore(versioning): bump version to 3.6.4 and fill the changelog

### PR DESCRIPTION
**Pull request by StackOverflowExcept1on**
@koute please review

### CODE REVIEW

**Comment by koute** [comment]
@StackOverflowExcept1on You also need to bump the derive crate's version.

**Review by bkchr — APPROVED** [review]

**Comment by bkchr** [comment]
@StackOverflowExcept1on you also need to change the `Cargo.toml` to import `derive` by `=>3.6.4`

**Review by ggwpez — APPROVED** [review]

**Review by koute — APPROVED** [review]

**Comment by koute** [comment]
[Released on crates.io](https://crates.io/crates/parity-scale-codec/3.6.4)

**Comment by StackOverflowExcept1on** [comment]
@koute we probably need to tag and release: https://github.com/paritytech/parity-scale-codec/releases

**Pull request merged**
