### PR TITLE
[ci] add cargo-nono

### PR DESCRIPTION
**Pull request by alvicsam**
close https://github.com/paritytech/ci_cd/issues/681

### CODE REVIEW

**Comment by alvicsam** [comment]
I've added `cargo-nono` but it fails. Should it have any additional options?

**Comment by jsdw** [comment]
I believe you need to add something like `--no-default-features` so that "std" isn't enabled by default.

**Review by oleg-plakida — APPROVED** [review]

**Comment by alvicsam** [comment]
Actually I didn't. @gilescope told me about the tool so I assumed that he already tested it

**Comment by jsdw** [comment]
Sadly, I tried adding this to `src/lib.rs`:

```rust
use std::collections::HashMap;
pub fn has_map<K, V>(_map: HashMap<K, V>) {
	let _m: HashMap<u32, u32> = HashMap::new();
	todo!()
}
```

I'd have expected that to cause `cargo nono check --no-default-features` to fail. I wonder whether it only checks that the packages used are marked "no-std" rather than specifically checking for compat.

I got this advice from https://blog.dbrgn.ch/2019/12/24/testing-for-no-std-compatibility/.

One of the other things it suggested is running:

```
rustup target add thumbv6m-none-eabi
cargo build --target thumbv6m-none-eabi --no-default-features
```

If I do that, it compiles OK without my addition adbove and fails to compile if I try importing `std::collections::HashMap`.

I'm not sure if there is value in both that _and_ `cargo nono` but offhand that seems like the way to go to me!

**Review by jsdw — APPROVED** [review]
LGTM; let's see how it pans out :)

**Pull request merged**
