### PR TITLE
Improve doc encodelike and implement some more.

### PR DESCRIPTION
**Pull request by thiolliere**
Fix https://github.com/paritytech/parity-scale-codec/issues/156

### CODE REVIEW

**Comment by bkchr** [comment]
```
diff --git a/src/codec.rs b/src/codec.rs
index f67b1b8..9cecab7 100644
--- a/src/codec.rs
+++ b/src/codec.rs
@@ -297,6 +297,7 @@ pub trait WrapperTypeEncode: Deref {}
 impl<T: ?Sized> WrapperTypeEncode for Box<T> {}
 impl<T: ?Sized + Encode> EncodeLike for Box<T> {}
 impl<T: Encode> EncodeLike<T> for Box<T> {}
+impl<T: Encode> EncodeLike<T> for Box<&T> {}
 
 impl<'a, T: ?Sized> WrapperTypeEncode for &'a T {}
 impl<'a, T: Encode> EncodeLike for &'a T {}
diff --git a/src/encode_like.rs b/src/encode_like.rs
index 9dcd4fc..6b74c37 100644
--- a/src/encode_like.rs
+++ b/src/encode_like.rs
@@ -83,6 +83,15 @@ mod tests {
                assert_eq!(slice_encoded, data_encoded);
        }
 
+       #[test]
+       fn test_box() {
+               let data = 10u32;
+               let encoded = data.encode();
+               let encoded2 = ComplexStuff::<Box<&u32>>::complex_method(&10u32);
+
+               assert_eq!(encoded, encoded2);
+       }
+
        #[test]
        fn interface_testing() {
                let value = 10u32;
```

It works?

**Comment by thiolliere** [comment]
oh yes indeed then we can implement way more than just those I try to come up with something. it is just about iterating on lots of combination

**Comment by bkchr** [comment]
I would more like mention in the documentation that we probably missed some combinations and accept prs to add these new combinations. And you could mention that this is not "design limitation", it is a flaw of rust that does not supports specialization..

**Comment by thiolliere** [comment]
though the number of combination seems quite explosive like combinations such as
```rust
impl<A: Encode, B: Encode> EnodeLike<(A, B)> for Box<(A, &B)> {}
```
should be written. thus if we want to support an ok set of tuple the number of combination might be huge.

**Comment by thiolliere** [comment]
also if a user defined two struct say that on encode like the other he has to implement all the combination of them inside box and tuple and vec and reference as well.

But might be an ok solution, do you have an idea of the number of implementation rustc can handle ?

**Pull request merged**
