### PR TITLE
move to rust 2021

### PR DESCRIPTION
**Pull request by NukeManDan**
Confirmed to build locally on Ubuntu 20.04.3 LTS:
```
rustc 1.56.1 (59eed8a2a 2021-11-01)
rustc 1.58.0-nightly (e90c5fbbc 2021-11-12)
```

### CODE REVIEW

**Review by bkchr — APPROVED** [review]

**Comment by bkchr** [comment]
@NukeManDan you need to update the ui tests

**Comment by NukeManDan** [comment]
`rust-version = "1.56.1"` introduced

For reference, I tried to get this to `cargo build` with 1.56.0 and it failed with
```
error: package `...` cannot be built because it requires rustc 1.56.1 or newer, while the currently active rustc version is 1.56.0
```
With `--ignore-rust-version` it _does_ build with 1.56.0, as expected.

**Comment by NukeManDan** [comment]
bench-rust-nightly = `cargo +nightly bench --features bit-vec,generic-array,derive` throws a lot of build warnings, but passes. Also test reports like:
```
vec_decode_no_limit_u8/131072                                                                             
                        time:   [5.5258 us 5.5443 us 5.5708 us]
Found 12 outliers among 100 measurements (12.00%)
  4 (4.00%) high mild
  8 (8.00%) high severe
```
for example (running locally).


`cargo +nightly miri test --features bit-vec,generic-array,arbitrary --release` :
```
error: the 'miri' component which provides the command 'cargo-miri' is not available for the 'nightly-x86_64-unknown-linux-gnu' toolchain
```
I assume this is expected on an x86 machine? What does this run on :sweat_smile: ?

**Comment by NukeManDan** [comment]
https://gitlab.parity.io/parity/parity-scale-codec/-/jobs/1235195

I see the env variables are somehow not getting picked up? I will try with `TRYBUILD=overwrite` and put in another commit to see if the next one is clean... It passes locally!

**Pull request merged**
